spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

razorpay.key=rzp_test_RggzGpdUJuULc1
razorpay.secret=frhYpb9cQnSBXDBD64HMe6jg